services:
  admininterface.server:
    image: ${DOCKER_REGISTRY-}admininterfaceserver
    ports:
      - 5000:80
    build:
      context: .
      dockerfile: AdminInterface/AdminInterface.Server/Dockerfile
<<<<<<< Updated upstream
=======
    depends_on:
      - mysql
>>>>>>> Stashed changes
    networks: 
      - dev-network

  admininterface.client:
    image: admininterfaceclient
    build:
      context: AdminInterface/admininterface.client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - admininterface.server
    networks: 
      - dev-network

<<<<<<< Updated upstream
=======
  mysql:
    image: mysql:latest
    restart: always
    environment:
        MYSQL_DATABASE: 'innovationprojet2025'
        MYSQL_ROOT_PASSWORD: 'root'
    ports:
        - 3306:3306
    expose:
        - 3306
    volumes:
        - db:/var/lib/mysql
        - ./db:/docker-entrypoint-initdb.d
    networks:
      - dev-network

volumes:
  db:

>>>>>>> Stashed changes
networks:
  dev-network: {}    